### ISSUE TITLE
Free license v1.2.0: Patent Defense section references old griffarins site

### ISSUE THREAD

**Issue by jeremy-w** [indiecc/indiecc.com#1]
Language begins:

> If you make any written claim that software offered for sale through griffarins.com…

Two things here:

- URL probably needs updating to indiecc.com
- It would be nice to have this more directly refer to the licensed project, in addition to indiecc, to make the license more useful for projects not part of indiecc. Perhaps “…claim that **this software or any** software offered for sale through…”

**Comment by kemitchell** [comment]
Thanks so much!
