### ISSUE TITLE
Free License v1.2.0: Dead link from Excuse to anchor #share

### ISSUE THREAD

**Issue by jeremy-w** [indiecc/indiecc.com#2]
It looks like the section is now titled “Improvements”. Though that is an odd name for an obligation, and “Share Improvements with Developer” would be far clearer, or just “Share Improvements” to work a verb and the sharing requirement in their. (Pretty sure they’re not obliged to _make_ improvements after all. Save that for the Boy Scout License that requires leaving the code better than you found it… 😉)

(The “with developer” part seems distinctive enough to be worth including in a heading, vs the more usual “with the world by publishing it”.)

**Comment by kemitchell** [comment]
Thanks so much for this. I thought I was checking all links automatically, but that doesn't appear to be working for #-links.

I spotted a couple other issues here. And I will be improving the headings.

**Comment by jeremy-w** [comment]
v1.2.2 looks great! I think I finally have a decision on license for this [side project](https://macchiato.10centuries.org/) I’ve been meaning to release the source for. 😊

**Comment by kemitchell** [comment]
@jeremy-w thanks for all your input! FYI, I just pushed a version 1.2.3, with a few small readability improvements, as well.

Would love to have you on indiecc.com if you're up for it. I've done a lot of work on the platform, and feel really good about it. Needs tire-tickers!

**Comment by jeremy-w** [comment]
Ah, nice!

I found it hard to view diffs between versions on GitHub and IndieCC, because of the per-file approach that keeps old versions still accessible. I think one workaround would be to commit a new version with the text of the old version, then commit the edit to actually add the text, so the update commit is still readily diffable against the old. (For now, I just manually saved off the two and diffed them.)

This project is an end-user app, so it seems a poor fit for the sort of reusable, licensable modules I understand IndieCC as looking to facilitate sharing. Or have I misunderstood IndieCC’s aims?

**Comment by kemitchell** [comment]
The site serves all versions of every license, terms of service, privacy notice, etc. I don't think GitHub allows diffing of different files, but you can clone the repo and do `cd terms/free ; diff $old $new`. I suppose I could also add an endpoint to serve those diffs automatically.
